apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: userprofile
        image: registryrhx6769.azurecr.io/userprofile:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          value: "sqladminrHx6769"
        - name: SQL_PASSWORD
          value: "Containerlab4"
        - name: SQL_SERVER
          value: "sqlserverrhx6769.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: api
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: userprofile