apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  name: tripviewer-ingress
  namespace: web
spec:
  rules:
  - host: 254bd7497bc346ab832b.westus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: tripviewer
          servicePort: 80
        path: /
